/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientePagamentosRouteImport } from './routes/cliente.pagamentos'
import { Route as ClienteNegociacaoRouteImport } from './routes/cliente.negociacao'
import { Route as ClienteHistoricoRouteImport } from './routes/cliente.historico'
import { Route as ClienteDividasRouteImport } from './routes/cliente.dividas'
import { Route as ClienteDashboardRouteImport } from './routes/cliente.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientePagamentosRoute = ClientePagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteNegociacaoRoute = ClienteNegociacaoRouteImport.update({
  id: '/negociacao',
  path: '/negociacao',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteHistoricoRoute = ClienteHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteDividasRoute = ClienteDividasRouteImport.update({
  id: '/dividas',
  path: '/dividas',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/dividas': typeof ClienteDividasRoute
  '/cliente/historico': typeof ClienteHistoricoRoute
  '/cliente/negociacao': typeof ClienteNegociacaoRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/dividas': typeof ClienteDividasRoute
  '/cliente/historico': typeof ClienteHistoricoRoute
  '/cliente/negociacao': typeof ClienteNegociacaoRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cliente': typeof ClienteRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/dividas': typeof ClienteDividasRoute
  '/cliente/historico': typeof ClienteHistoricoRoute
  '/cliente/negociacao': typeof ClienteNegociacaoRoute
  '/cliente/pagamentos': typeof ClientePagamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cliente'
    | '/esqueci-senha'
    | '/admin/dashboard'
    | '/cliente/dashboard'
    | '/cliente/dividas'
    | '/cliente/historico'
    | '/cliente/negociacao'
    | '/cliente/pagamentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cliente'
    | '/esqueci-senha'
    | '/admin/dashboard'
    | '/cliente/dashboard'
    | '/cliente/dividas'
    | '/cliente/historico'
    | '/cliente/negociacao'
    | '/cliente/pagamentos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cliente'
    | '/esqueci-senha'
    | '/admin/dashboard'
    | '/cliente/dashboard'
    | '/cliente/dividas'
    | '/cliente/historico'
    | '/cliente/negociacao'
    | '/cliente/pagamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClienteRoute: typeof ClienteRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/pagamentos': {
      id: '/cliente/pagamentos'
      path: '/pagamentos'
      fullPath: '/cliente/pagamentos'
      preLoaderRoute: typeof ClientePagamentosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/negociacao': {
      id: '/cliente/negociacao'
      path: '/negociacao'
      fullPath: '/cliente/negociacao'
      preLoaderRoute: typeof ClienteNegociacaoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/historico': {
      id: '/cliente/historico'
      path: '/historico'
      fullPath: '/cliente/historico'
      preLoaderRoute: typeof ClienteHistoricoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/dividas': {
      id: '/cliente/dividas'
      path: '/dividas'
      fullPath: '/cliente/dividas'
      preLoaderRoute: typeof ClienteDividasRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/dashboard': {
      id: '/cliente/dashboard'
      path: '/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteRouteChildren {
  ClienteDashboardRoute: typeof ClienteDashboardRoute
  ClienteDividasRoute: typeof ClienteDividasRoute
  ClienteHistoricoRoute: typeof ClienteHistoricoRoute
  ClienteNegociacaoRoute: typeof ClienteNegociacaoRoute
  ClientePagamentosRoute: typeof ClientePagamentosRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteDashboardRoute: ClienteDashboardRoute,
  ClienteDividasRoute: ClienteDividasRoute,
  ClienteHistoricoRoute: ClienteHistoricoRoute,
  ClienteNegociacaoRoute: ClienteNegociacaoRoute,
  ClientePagamentosRoute: ClientePagamentosRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClienteRoute: ClienteRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
